#java 所有应用及服务
# p-dts-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-dts-service
  labels:
    app: p-dts-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-dts-service
  template:
    metadata:
      labels:
        app: p-dts-service
    spec:
      containers:
        - name: p-dts-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-dts-service-0.0.1-SNAPSHOT.jar /root/p-dts-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx4096m p-dts-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9101
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-dts-service
apiVersion: v1
kind: Service
metadata:
  name: p-dts-service
spec:
  ports:
    - port: 9101
      protocol: TCP
      targetPort: 9101
  selector:
    app: p-dts-service
  type: ClusterIP
---
# p-msg-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-msg-service
  labels:
    app: p-msg-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-msg-service
  template:
    metadata:
      labels:
        app: p-msg-service
    spec:
      containers:
        - name: p-msg-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-msg-service-0.0.1-SNAPSHOT.jar /root/p-msg-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx4096m p-msg-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9051
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-msg-service
apiVersion: v1
kind: Service
metadata:
  name: p-msg-service
spec:
  ports:
    - port: 9051
      protocol: TCP
      targetPort: 9051
  selector:
    app: p-msg-service
  type: ClusterIP
---
# p-account-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-account-service
  labels:
    app: p-account-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-account-service
  template:
    metadata:
      labels:
        app: p-account-service
    spec:
      containers:
        - name: p-account-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-account-service-0.0.1-SNAPSHOT.jar /root/p-account-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx6144m p-account-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "6Gi"
              cpu: "1000m"
            limits:
              memory: "7Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9011
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-account-service
apiVersion: v1
kind: Service
metadata:
  name: p-account-service
spec:
  ports:
    - port: 9011
      protocol: TCP
      targetPort: 9011
  selector:
    app: p-account-service
  type: ClusterIP
---
# p-borrow-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-borrow-service
  labels:
    app: p-borrow-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-borrow-service
  template:
    metadata:
      labels:
        app: p-borrow-service
    spec:
      containers:
        - name: p-borrow-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-borrow-service-0.0.1-SNAPSHOT.jar /root/p-borrow-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx4096m p-borrow-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9021
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-borrow-service
apiVersion: v1
kind: Service
metadata:
  name: p-borrow-service
spec:
  ports:
    - port: 9021
      protocol: TCP
      targetPort: 9021
  selector:
    app: p-borrow-service
  type: ClusterIP
---
# p-invest-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-invest-service
  labels:
    app: p-invest-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-invest-service
  template:
    metadata:
      labels:
        app: p-invest-service
    spec:
      containers:
        - name: p-invest-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-invest-service-0.0.1-SNAPSHOT.jar /root/p-invest-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx4096m p-invest-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9031
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-invest-service
apiVersion: v1
kind: Service
metadata:
  name: p-invest-service
spec:
  ports:
    - port: 9031
      protocol: TCP
      targetPort: 9031
  selector:
    app: p-invest-service
  type: ClusterIP
---
# p-notification-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-notification-service
  labels:
    app: p-notification-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-notification-service
  template:
    metadata:
      labels:
        app: p-notification-service
    spec:
      containers:
        - name: p-notification-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-notification-service-0.0.1-SNAPSHOT.jar /root/p-notification-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx4096m p-notification-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9061
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-notification-service
apiVersion: v1
kind: Service
metadata:
  name: p-notification-service
spec:
  ports:
    - port: 9061
      protocol: TCP
      targetPort: 9061
  selector:
    app: p-notification-service
  type: ClusterIP
---
# p-depository-service
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-depository-service
  labels:
    app: p-depository-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-depository-service
  template:
    metadata:
      labels:
        app: p-depository-service
    spec:
      containers:
        - name: p-depository-service
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-depository-service-0.0.1-SNAPSHOT.jar /root/p-depository-service-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx4096m p-depository-service-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9111
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-depository-service
apiVersion: v1
kind: Service
metadata:
  name: p-depository-service
spec:
  ports:
    - port: 9111
      protocol: TCP
      targetPort: 9111
  selector:
    app: p-depository-service
  type: ClusterIP
---
# p-core-admin
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-core-admin
  labels:
    app: p-core-admin
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-core-admin
  template:
    metadata:
      labels:
        app: p-core-admin
    spec:
      containers:
        - name: p-core-admin
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-core-admin-0.0.1-SNAPSHOT.jar /root/p-core-admin-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx2048m p-core-admin-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9003
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-core-admin
apiVersion: v1
kind: Service
metadata:
  name: p-core-admin
spec:
  ports:
    - nodePort: 30903
      port: 9003
      protocol: TCP
      targetPort: 9003
  selector:
    app: p-core-admin
  type: NodePort
---
# p-api
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p-api
  labels:
    app: p-api
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
    # minReadySeconds: 20
    # strategy:
      # rollingUpdate:
        # maxSurge: 1
        # maxUnavailable: 0
      # type: RollingUpdate
  selector:
    matchLabels:
      app: p-api
  template:
    metadata:
      labels:
        app: p-api
    spec:
      containers:
        - name: p-api
          image: yjd-registry-vpc.cn-shanghai.cr.aliyuncs.com/java/java-run:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pvc-oss-p-java-jar
              mountPath: "/www"
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - cd /www
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: httpservername
              valueFrom:
                configMapKeyRef:
                  key: httpservername
                  name: httpservername
            - name: COMMAND0
              value: ' '
            - name: COMMAND1
              value: 'cp /www/jar/p-java-common/p-api-0.0.1-SNAPSHOT.jar /root/p-api-0.0.1-SNAPSHOT.jar'
            - name: COMMAND2
              value: 'nohup java -jar -Xms1024m -Xmx6144m p-api-0.0.1-SNAPSHOT.jar &'
            - name: TAG
              value: 'v20190729'
          resources:
            requests:
              memory: "6Gi"
              cpu: "1000m"
            limits:
              memory: "7Gi"
              cpu: "1200m"
          ports:
            - containerPort: 9081
      dnsPolicy: ClusterFirst
      restartPolicy: Always           
      imagePullSecrets:
        - name: aliyun-hub
      volumes:
        - name: pvc-oss-p-java-jar
          persistentVolumeClaim:
            claimName: pvc-oss-p-java-jar
---
# p-api
apiVersion: v1
kind: Service
metadata:
  name: p-api
spec:
  ports:
    - port: 9081
      protocol: TCP
      targetPort: 9081
  selector:
    app: p-api
  type: ClusterIP
